### ISSUE TITLE
Doesn't appear to copy anything to the clipboard

### ISSUE THREAD

**Issue by cattledogit** [igorlogius/copy-taburl-html#1]
It doesn't appear to copy anything to the clipboard. Perhaps this is because it doesn't request the activeTab permission (a.k.a. "Access browser tabs"??) ? Thanks for this addon, especially "This add-on tries to use the minimal number of required permissions to successfully fullfill its intended purpose."

**Comment by igorlogius** [comment]
Should be resolved within version 1.0.6 (had to make a few more changes, but now it should work as expected.)
