### ISSUE TITLE
Missing Dark Mode Icon

### ISSUE THREAD

**Issue by SandmanPSU** [igorlogius/copy-taburl-html#2]
Functional everything with this add-on is great, but it is missing one small HMI feature. The icon color on a dark background is still black and very hard to see. (see image below) Please add an white icon for dark mode. Thanks.

![image](https://user-images.githubusercontent.com/108283599/175963317-3e2269a2-ad6a-4915-82b4-30d75379ca49.png)

**Comment by igorlogius** [comment]
I am not a graphics designer, so i hope this is good enough:

![icon_2](https://user-images.githubusercontent.com/67047467/176004078-c2f93dd4-0ac0-4780-9e6d-10929a62f0dc.png)

If not, i am open for suggestions / pull requests.

**Comment by igorlogius** [comment]
@SandmanPSU  
I think this 

![index](https://user-images.githubusercontent.com/67047467/176009663-38f52bc9-c970-4fd7-81e7-f3d79ae99158.png)

was the original. Or at least it is close enough. 
I just made the slight modifications  of adding the tags `<` and `>`  around the link icon.

**Comment by SandmanPSU** [comment]
Ok, I am not an expert here, but I believe you can use a combination of two online tools to make the icon compatible for both light and dark themes:
1. Convert the PNG to SVG: https://convertio.co/png-svg/
2. Upgrade the Icon to support Dark Theme by inverting the colors: https://realfavicongenerator.net/svg-favicon/

**Comment by igorlogius** [comment]
@SandmanPSU  The generated SVG  seems to be context aware ... 
I did not know that was possible to use in this situation. 
Pretty neat. I'll update the addon with the new icon.

**Comment by igorlogius** [comment]
![capture-2022-06-27_22:40:24](https://user-images.githubusercontent.com/67047467/176031870-17d535a3-136c-4bfe-92eb-af0636a43cd6.jpg)

**Comment by SandmanPSU** [comment]
I got the update, and it looks great. Thanks for the quick turnaround on this.
![image](https://user-images.githubusercontent.com/108283599/176181350-5c4558d0-af2c-4dfe-af99-dcc043e8bf7c.png)

It is missing the "<" ">" that you added to it, but now that you know about the SVG stuff, you should be able to add that back in if you want.
